version: '3.7'
services:
  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"

  celery-png:
    build: .
    command: celery -A resize_pics worker -l INFO -Q png
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app/
    links:
      - db
      - redis
    depends_on:
      - redis

  celery-jpg:
    build: .
    command: celery -A resize_pics worker -l INFO -Q jpg
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app/
    links:
      - db
      - redis
    depends_on:
      - redis
volumes:
  media: