# Generated by Django 3.1.2 on 2020-10-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resize_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='picture',
        ),
    ]
