# Generated by Django 3.1.2 on 2020-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_api', '0003_auto_20201015_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.BinaryField(blank=True),
        ),
    ]
