# Generated by Django 3.1.2 on 2020-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_api', '0004_auto_20201015_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
