# Generated by Django 3.1.2 on 2020-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resize_api', '0005_auto_20201015_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
